- name: Install base nrpe
  apt: name={{ item }} state=present
  with_items:
    - nagios-nrpe-server

- name: Stop nrpe
  service: 
    name: nagios-nrpe-server
    state: stopped

- name: Install patched nrpe binary
  copy:
    dest: '/usr/sbin/'
    src: '{{ NRPE_CLONE_DIR }}/src/nrpe'
    force: yes

- name: Start nrpe
  service: 
    name: nagios-nrpe-server
    state: started

